services:
  usv-proxy:
    build: .
    container_name: usv-proxy
    ports:
      - "${HOST_PORT:-3001}:3000"
    restart: always
    # Limitari clare de RAM aplicate la nivel de Docker daemon (Containerul va fi oprit de Docker inainte sa ocupe prea mult VPS-ul)
    deploy:
      resources:
        limits:
          memory: 180M
        reservations:
          memory: 50M
